apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-server-conf
  labels:
    name: grafana-server-conf
  namespace: monitoring
data:
  datasources.yml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      uid: 1
      url: http://prometheus-service:8080/
      basicAuth: false
      editable: true
      version: 1
      isDefault: true
