apiVersion: v1
kind: Service
metadata:
  name: pushgateway-service
spec:
  selector: 
    app: pushgateway-server
  type: NodePort
  ports:
    - port: 8120
      targetPort: 9091
      nodePort: 30040
