apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway-deployment
  namespace: monitoring
  labels:
    app: pushgateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway-server
  template:
    metadata:
      labels:
        app: pushgateway-server
    spec:
      containers:
        - name: pushgateway
          image: prom/pushgateway:latest
          ports:
            - containerPort: 9091
